on: push
jobs:
  update_docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r ./docs/requirements.txt
    - name: Make docs
      working-directory: ./docs
      run: make html
    - name: Move docs
      working-directory: ./docs
      run: rsync -a ./build/html/* ./
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        default_author: user_info
        message: 'update docs'
